// Send-through-system for PHYSICAL letters — the Pingen analogue of
// lib/marketing-email.approveAndSend. ONE auditable path that concentrates every
// gate so no caller can bypass them (docs/archive/EMAIL_SUBSYSTEM_SPIKE.md §4):
//
//   1. FLAG — PHYSICAL_MAIL_SENDS_APPROVED must be on (Pingen is a NEW processor
//      → CH → Deutsche Post; needs its own DPA). OFF ⇒ nothing is posted.
//   2. ADDRESS — the recipient must have a COMPLETE, LAWFULLY-held postal address
//      (lib/physical-address). No address / incomplete ⇒ refuse; never part-fill.
//   3. CONTENT — the customer's SEPARATE, letter-optimised draft (migration 0023:
//      letter_draft_subject/body, generated by generateCustomerLetterDraft — its
//      OWN text, distinct from the email) is rendered to a letter PDF with the
//      address block where Pingen reads it (address_position 'left').
//   4. SUBMIT — Pingen uploadAndCreate (auto_send) with an Idempotency-Key seeded
//      by the physical_letters row id, so a retry never prints twice.
//
// "Brief senden" is its OWN flow: the operator generates a letter draft (separate
// from the email), reviews/edits it, then sends → letter PDF → Pingen → status.

import { getCustomerById } from "./customer-store";
import { decidePhysicalEligibility } from "./physical-address.mjs";
import {
  createPhysicalLetter,
  markPhysicalLetterFailed,
  markPhysicalLetterSubmitted,
  type RecipientAddress,
} from "./physical-letters-store";
import { buildLetterPdf, letterPageCount } from "./letter-pdf.mjs";
import { isPingenConfigured, uploadAndCreate } from "./pingen";
import { isPhysicalMailSendsApproved } from "./pingen-flag.mjs";
import type { Customer } from "./customer-store";
import { reportError } from "./observability";

/** The shape physical-address.decidePhysicalEligibility returns (typed here so
 *  the .mjs stays plain). */
export interface PhysicalEligibility {
  eligible: boolean;
  reasonCode: string | null;
  reason: string | null;
  address: RecipientAddress | null;
}

/**
 * Compute physical-mail eligibility for a customer — the single source of truth
 * behind both the disabled "Brief senden" button (page.tsx) and the server
 * refusal below. Reads the lawful address store + the flag + Pingen config.
 */
export function physicalEligibilityForCustomer(
  customer: Pick<Customer, "id" | "postalAddress" | "postalAddressSource" | "postalAddressInvalidAt"> & {
    postalObjectionAt?: string | null;
  }
): PhysicalEligibility {
  return decidePhysicalEligibility({
    flagApproved: isPhysicalMailSendsApproved(),
    pingenConfigured: isPingenConfigured(),
    address: customer.postalAddress ?? null,
    postalObjectionAt: customer.postalObjectionAt ?? null,
    // Only the shipping address of a completed order counts (dossier § 6.4).
    addressSource: customer.postalAddressSource ?? null,
    addressInvalidAt: customer.postalAddressInvalidAt ?? null,
  }) as PhysicalEligibility;
}

export type SendPhysicalLetterResult =
  | { ok: true; letterId: number; providerLetterId: string; status: string }
  | {
      ok: false;
      reason:
        | "not_found"
        | "no_draft"
        | "objection"
        | "flag_off"
        | "no_address"
        | "incomplete_address"
        | "not_purchase_address"
        | "address_invalid"
        | "pingen_not_configured"
        | "submit_failed"
        | "store_failed";
      message: string;
    };

/**
 * Submit a physical letter for a customer using their SEPARATE letter draft
 * (migration 0023) — the "Brief senden" action. Never throws — returns a typed
 * refusal/result.
 */
export async function sendPhysicalLetter(customerId: number): Promise<SendPhysicalLetterResult> {
  try {
    const customer = await getCustomerById(customerId);
    if (!customer) return { ok: false, reason: "not_found", message: "Kunde nicht gefunden." };

    // GATES 1+2 (+ config) in one decision — the same one the UI used to enable
    // the button, re-checked server-side (defense in depth, fail-closed).
    const eligibility = physicalEligibilityForCustomer(customer);
    if (!eligibility.eligible || !eligibility.address) {
      const reason = (eligibility.reasonCode ?? "no_address") as
        | "objection"
        | "flag_off"
        | "no_address"
        | "incomplete_address"
        | "not_purchase_address"
        | "address_invalid"
        | "pingen_not_configured";
      return { ok: false, reason, message: eligibility.reason ?? "Nicht versandfähig." };
    }
    const recipient = eligibility.address;

    // The letter has its OWN draft (distinct from the email). No draft ⇒ refuse.
    const body = customer.letterDraftBody?.trim();
    if (!body) {
      return {
        ok: false,
        reason: "no_draft",
        message: "Kein Brief-Entwurf vorhanden — bitte zuerst einen Brief-Entwurf generieren.",
      };
    }

    return await submitLetter({
      customerId: customer.id,
      recipient,
      subject: customer.letterDraftSubject,
      body,
    });
  } catch (err) {
    reportError(err, { route: "lib/physical-mail", phase: "sendPhysicalLetter" });
    return { ok: false, reason: "submit_failed", message: "Unerwarteter Fehler beim Versand." };
  }
}

export type SubmitLetterResult =
  | { ok: true; letterId: number; providerLetterId: string; status: string; pageCount: number }
  | { ok: false; reason: "store_failed" | "submit_failed"; message: string; letterId: number | null };

/**
 * The ONE place a letter is handed to Pingen (Kunden → Brief and the campaign
 * channel) — called only AFTER the caller's gates passed. Renders the PDF
 * (address block where Pingen reads it, the deterministic Art. 21 notice and
 * company footer on every page), creates the audit row FIRST (its id seeds the
 * Idempotency-Key, so a retry never prints twice), lets the caller attach that
 * row (`onCreated`) before the submission, then submits with auto_send.
 */
export async function submitLetter(input: {
  customerId: number;
  recipient: RecipientAddress;
  subject: string | null;
  body: string;
  campaignId?: number | null;
  onCreated?: (letterId: number) => Promise<boolean>;
}): Promise<SubmitLetterResult> {
  const pdf = buildLetterPdf({ recipient: input.recipient, subject: input.subject, body: input.body });
  const pageCount = letterPageCount(input.body);
  const letterId = await createPhysicalLetter({
    customerId: input.customerId,
    marketingSendId: null,
    campaignId: input.campaignId ?? null,
    recipient: input.recipient,
    subject: input.subject,
    body: input.body,
  });
  if (letterId == null) {
    return { ok: false, reason: "store_failed", message: "Brief konnte nicht angelegt werden (DB).", letterId: null };
  }
  if (input.onCreated && !(await input.onCreated(letterId))) {
    await markPhysicalLetterFailed(letterId, "not attached — not submitted");
    return { ok: false, reason: "store_failed", message: "Brief konnte nicht zugeordnet werden (DB).", letterId };
  }

  // Pingen uploadAndCreate (auto_send). Idempotency-Key keyed by the row.
  const result = await uploadAndCreate({
    pdf,
    fileOriginalName: `brief-${letterId}.pdf`,
    idempotencyKey: `physical-letter-${letterId}`,
    autoSend: true,
    options: { addressPosition: "left", deliveryProduct: "fast", printSpectrum: "grayscale" },
  });
  if (!result.ok) {
    await markPhysicalLetterFailed(letterId, result.message);
    return { ok: false, reason: "submit_failed", message: `Pingen: ${result.message}`, letterId };
  }
  await markPhysicalLetterSubmitted(letterId, result.letter.id, result.letter.status, result.letter.costCents);
  return { ok: true, letterId, providerLetterId: result.letter.id, status: result.letter.status, pageCount };
}
