-- 0032_analytics_reports.sql — the "Komplettanalyse" feature: a stored, dense,
-- structured analytics overview for a chosen time interval, generated by running
-- ALL of the app's AI analysis features over that window IN ONE GO, and kept so
-- the team can switch between past reports in the side panel and re-download them
-- as PDF without re-spending tokens.
--
-- One row per generated report. The generation is INCREMENTAL and client-driven
-- (the same "process a batch, report what remains, run again" pattern the bulk
-- conversation analysis uses — see /api/admin/conversations/analyze-bulk), so a
-- big interval with hundreds of conversations never blocks a single request past
-- maxDuration. The row therefore carries its own progress state-machine:
--
--   status  — running | complete | failed  (the lifecycle the sidebar shows)
--   phase   — which generation phase is active (analyze → insights → personas →
--             customer_synthesis → customer_profiles → assemble → done)
--   progress— JSONB counters + transient work-queues the stepper reads/writes
--   options — JSONB feature switches chosen at creation (per-customer profiles,
--             appendix, caps)
--   sections— JSONB: the assembled, render-ready report payload (filled phase by
--             phase, completed in `assemble`). NULL until the first phase writes.
--   usage   — JSONB per-model {input,output} token sums, so the EUR cost is
--             priced in JS via lib/ai-pricing.mjs (one source of truth) and shown
--             for free on every later read — like the rest of the cost KPIs.
--
-- GDPR / data clusters: most of a report is pseudonymous Cluster-A analytics
-- (conversation analysis, insights, persona breakdown, top questions) — no email,
-- no identity. The OPTIONAL per-customer "customer knowledge" section
-- (options.includePerCustomer) folds in the identity-linked "current
-- understanding" profile (Cluster B), so a completed report's `sections` is a
-- SNAPSHOT that may contain customer display names. That is a deliberate, admin-
-- only, operator-chosen inclusion for the team's decision-making; the report is
-- only ever reachable behind the admin gate (proxy + guardAdminPost).
--
-- The report row carries NO FK to a customer/conversation (it is derived text),
-- so — like the existing derived caches (conversation_insights,
-- kpi_persona_question_summaries) — it is NOT auto-purged by the retention sweep
-- and a snapshot does NOT cascade-delete when its source customer is erased. It is
-- managed MANUALLY: an operator deletes a report from the side panel. Operational
-- note: when honouring an erasure that included per-customer profiles, also delete
-- any report generated with the per-customer option that covered that customer.

CREATE TABLE IF NOT EXISTS analytics_reports (
  id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  -- Human-readable title shown in the sidebar, e.g. "Komplettanalyse · Juni 2026".
  -- Auto-derived from the interval at creation; editable later is out of scope.
  title           TEXT NOT NULL,
  -- The inclusive interval the report covers (same calendar-window semantics as
  -- the KPI / inspector date filters — see lib/kpi-range).
  date_from       DATE NOT NULL,
  date_to         DATE NOT NULL,
  -- Which picker option produced the window ('7d'|'30d'|'90d'|'custom'|'day'|
  -- 'week'|'month'), kept for display only.
  preset          TEXT NOT NULL DEFAULT 'custom',
  -- Lifecycle. A report is created 'running' and the client drives it to
  -- 'complete' (or 'failed' on a fatal error). Never auto-runs.
  status          TEXT NOT NULL DEFAULT 'running'
                    CHECK (status IN ('running', 'complete', 'failed')),
  -- Current generation phase (state machine key). 'done' once assembled.
  phase           TEXT NOT NULL DEFAULT 'analyze',
  -- Progress counters + transient work-queues the stepper reads/writes.
  progress        JSONB NOT NULL DEFAULT '{}'::jsonb,
  -- Feature switches chosen at creation (includePerCustomer, includeAppendix,
  -- maxProfiles, maxAnalyze, …).
  options         JSONB NOT NULL DEFAULT '{}'::jsonb,
  -- The assembled, render-ready report payload. NULL until generation writes it.
  sections        JSONB,
  -- Per-model token sums {model: {input, output}} → priced in JS (ai-pricing.mjs).
  usage           JSONB NOT NULL DEFAULT '{}'::jsonb,
  -- A short human-readable error when status = 'failed'.
  error           TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at    TIMESTAMPTZ
);

-- The sidebar lists reports newest-first; retention purges by age.
CREATE INDEX IF NOT EXISTS analytics_reports_created_idx
  ON analytics_reports (created_at DESC);
